# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/dshoreman/shop/models/category/columns.yaml

# Model Class name
modelClass: DShoreman\Shop\Models\Category

# List Title
title: Manage Categories

# Link URL for each record
recordUrl: dshoreman/shop/categories/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 25

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
defaultSort:
    column: sort_order
    direction: asc

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
